// Build-time intrinsic image dimensions for local /assets images, so components
// can emit real width/height attributes (CLS / Lighthouse "explicit width and
// height"). Reads from public/<src> with sharp (already an Astro dependency);
// results are cached per src so repeated gallery images cost one read per build.
import sharp from 'sharp';
import { existsSync } from 'node:fs';
import { join } from 'node:path';

const cache = new Map<string, { w: number; h: number } | null>();

// Return the `.sm.webp` sibling URL for a local jpg/png src IF it exists on disk
// (generated by scripts/gen-webp.mjs), else null — so callers can emit a <picture>
// <source> only when there's actually a WebP to serve.
const webpCache = new Map<string, string | null>();
export function smWebp(src: string): string | null {
  if (!src || src.startsWith('http') || !/\.(jpe?g|png)$/i.test(src)) return null;
  if (webpCache.has(src)) return webpCache.get(src)!;
  const url = src.replace(/\.(jpe?g|png)$/i, '.sm.webp');
  const out = existsSync(join('public', url)) ? url : null;
  webpCache.set(src, out);
  return out;
}

export async function imageSize(src: string): Promise<{ w: number; h: number } | null> {
  if (!src || src.startsWith('http')) return null;
  if (cache.has(src)) return cache.get(src)!;
  let dims: { w: number; h: number } | null = null;
  try {
    const m = await sharp(join('public', src)).metadata();
    if (m.width && m.height) dims = { w: m.width, h: m.height };
  } catch {
    dims = null; // missing/unreadable — emit no attributes rather than break the build
  }
  cache.set(src, dims);
  return dims;
}
